#include "Mapping.h"

GLuint BufferUsageMap [] =
{
	GL_STATIC_DRAW,	//BUFFER_USAGE_IMMUTABLE
	GL_STATIC_DRAW,	//BUFFER_USAGE_STATIC
	GL_DYNAMIC_DRAW,	//BUFFER_USAGE_DYNAMIC
	GL_STREAM_DRAW	//BUFFER_USAGE_STREAM
};

GLuint TextureUsageMap [] =
{
	0,	//TEXTURE_USAGE_STATIC
	0,	//TEXTURE_USAGE_WRITE_ONLY
	0	//TEXTURE_USAGE_READABLE
};

GLuint MapAccessMap [] =
{
	GL_READ_ONLY,	//MAP_READ_ONLY
	GL_READ_WRITE,	//MAP_READ_AND_WRITE
	GL_WRITE_ONLY,	//MAP_WRITE_INVALIDATE_ALL
	GL_WRITE_ONLY,	//MAP_WRITE_UNUSED_RANGE
	GL_WRITE_ONLY,	//MAP_WRITE_ONLY
	GL_WRITE_ONLY	//MAP_WRITE_INVALIDATE_RANGE
};





//Render States

GLuint MappingBlendFactor[] = 
{
	GL_ZERO,
	GL_ONE,
	GL_SRC_COLOR,
	GL_ONE_MINUS_SRC_COLOR,
	GL_SRC_ALPHA,
	GL_ONE_MINUS_SRC_ALPHA,
	GL_DST_ALPHA,
	GL_ONE_MINUS_DST_ALPHA,
	GL_DST_COLOR,
	GL_ONE_MINUS_DST_COLOR,
	GL_SRC_ALPHA_SATURATE,
	GL_CONSTANT_COLOR,
	GL_ONE_MINUS_CONSTANT_COLOR,
	GL_SRC1_COLOR,
	GL_ONE_MINUS_SRC1_COLOR,
	GL_SRC1_ALPHA,
	GL_ONE_MINUS_SRC1_ALPHA
};
GLuint MappingBlendFunc[] = 
{
	GL_FUNC_ADD,
	GL_FUNC_SUBTRACT,
	GL_FUNC_REVERSE_SUBTRACT,
	GL_MIN,
	GL_MAX
};
GLuint MappingRasterizerFill[] = 
{
	GL_LINE,
	GL_FILL
};
GLuint MappingRasterizerCull[] = 
{
	0, //RS_CULL_NONE
	GL_FRONT,
	GL_BACK
};
GLuint MappingStencilOp[] = 
{
	GL_KEEP,
	GL_ZERO,
	GL_REPLACE,
	GL_INCR,
	GL_DECR,
	GL_INVERT,
	GL_INCR_WRAP,
	GL_DECR_WRAP
};
GLuint MappingDSCompare[] = 
{
	GL_NEVER,
	GL_LESS,
	GL_EQUAL,
	GL_LEQUAL,
	GL_GREATER,
	GL_NOTEQUAL,
	GL_GEQUAL,
	GL_ALWAYS
};


GLuint MappingSamplerFilter_MAG [] =
{
	GL_NEAREST,			//FILTER_NEAREST_NEAREST_NEAREST,
	GL_NEAREST,	//FILTER_NEAREST_NEAREST_LINEAR,
	GL_LINEAR, //FILTER_NEAREST_LINEAR_NEAREST,
	GL_LINEAR,	//FILTER_NEAREST_LINEAR_LINEAR,
	GL_NEAREST,	//FILTER_LINEAR_NEAREST_NEAREST,
	GL_NEAREST,	//FILTER_LINEAR_NEAREST_LINEAR,
	GL_LINEAR,	//FILTER_LINEAR_LINEAR_NEAREST,
	GL_LINEAR,	//FILTER_LINEAR_LINEAR_LINEAR,
	GL_LINEAR,			//FILTER_ANISOTROPIC,
	GL_NEAREST,	//FILTER_COMP_NEAREST_NEAREST_NEAREST,
	GL_NEAREST,	//FILTER_COMP_NEAREST_NEAREST_LINEAR,
	GL_LINEAR,	//FILTER_COMP_NEAREST_LINEAR_NEAREST,
	GL_LINEAR,	//FILTER_COMP_NEAREST_LINEAR_LINEAR,
	GL_NEAREST,	//FILTER_COMP_LINEAR_NEAREST_NEAREST,
	GL_NEAREST,	//FILTER_COMP_LINEAR_NEAREST_LINEAR,
	GL_LINEAR,	//FILTER_COMP_LINEAR_LINEAR_NEAREST,
	GL_LINEAR,	//FILTER_COMP_LINEAR_LINEAR_LINEAR,
	GL_LINEAR		//FILTER_COMP_ANISOTROPIC,
};

GLuint MappingSamplerFilter_MIN_MIP [] =
{
	GL_NEAREST_MIPMAP_NEAREST,			//FILTER_NEAREST_NEAREST_NEAREST,
	GL_NEAREST_MIPMAP_LINEAR,	//FILTER_NEAREST_NEAREST_LINEAR,
	GL_NEAREST_MIPMAP_NEAREST, //FILTER_NEAREST_LINEAR_NEAREST,
	GL_NEAREST_MIPMAP_LINEAR,	//FILTER_NEAREST_LINEAR_LINEAR,
	GL_LINEAR_MIPMAP_NEAREST,	//FILTER_LINEAR_NEAREST_NEAREST,
	GL_LINEAR_MIPMAP_LINEAR,	//FILTER_LINEAR_NEAREST_LINEAR,
	GL_LINEAR_MIPMAP_NEAREST,	//FILTER_LINEAR_LINEAR_NEAREST,
	GL_LINEAR_MIPMAP_LINEAR,	//FILTER_LINEAR_LINEAR_LINEAR,
	GL_LINEAR_MIPMAP_LINEAR,			//FILTER_ANISOTROPIC,
	GL_NEAREST_MIPMAP_NEAREST,	//FILTER_COMP_NEAREST_NEAREST_NEAREST,
	GL_NEAREST_MIPMAP_LINEAR,	//FILTER_COMP_NEAREST_NEAREST_LINEAR,
	GL_NEAREST_MIPMAP_NEAREST,	//FILTER_COMP_NEAREST_LINEAR_NEAREST,
	GL_NEAREST_MIPMAP_LINEAR,	//FILTER_COMP_NEAREST_LINEAR_LINEAR,
	GL_LINEAR_MIPMAP_NEAREST,	//FILTER_COMP_LINEAR_NEAREST_NEAREST,
	GL_LINEAR_MIPMAP_LINEAR,	//FILTER_COMP_LINEAR_NEAREST_LINEAR,
	GL_LINEAR_MIPMAP_NEAREST,	//FILTER_COMP_LINEAR_LINEAR_NEAREST,
	GL_LINEAR_MIPMAP_LINEAR,	//FILTER_COMP_LINEAR_LINEAR_LINEAR,
	GL_LINEAR_MIPMAP_LINEAR		//FILTER_COMP_ANISOTROPIC,
};


GLuint MappingSamplerEdge[] = 
{
	GL_REPEAT,
	GL_MIRRORED_REPEAT,
	GL_CLAMP_TO_EDGE,
	GL_CLAMP_TO_BORDER
};

GLuint MappingPrimitiveType[] = 
{
	GL_TRIANGLES,
	GL_TRIANGLE_STRIP,
	GL_LINES
};


GLuint MappingSamplerType[] =
{
	GL_TEXTURE_1D,
	GL_TEXTURE_2D,
	GL_TEXTURE_3D,
	GL_TEXTURE_CUBE_MAP,
	0,
	0
};